### PR TITLE
Disable manifests & sync waves

### PR DESCRIPTION
**Pull request by jordigilh**
* Added sync waves to the application manifests
The waves are grouped as follows:
```
Sync wave 0
-------------------
Namespaces
Ansible-runner
CatalogSource
RBAC
User Workload Monitoring
User Management
Operators:
    ResourceLock
    Openshift Pipelines
    CNV
    Quay
    OCS

Sync wave 1
------------------- 
Operators (Nexus-Operator)
CNV Hyperconverged
ODF/Noobaa chart
RFE-pipelines (Depends on RBAC, namespaces and Operator (openshift-pipelines))

Sync wave 2
--------------------
 Nexus (Depends on OCS for PVC and ansible runner for ansible-rfe image stream)
 Quay (Depends on OCS for PVC and ansible runner for ansible-rfe image stream)
 
Sync wave 3
-------------------
 Image Builder VM (Depends on RBAC, CNV, Nexus and ansible-rfe image stream)

Sync wave 4
-------------------
 HTTPD (Depends on namespaces, image-builder-vm and ansible-rfe image stream)
```
* Replaced legacy helm hooks with argoCD hooks
* Removed Quay subscription from quay chart (it's already created via operator chart)
* Removed `sync-wave` annotations in deploy manifests (centralized them all in app manifests)
* Added the ability to disable application manifest generation when the chart has a field `disabled` with `true` value (boolean). Example:
```
application-manager:
  charts:
    # Top Level RFE App of App Chart
    rfe-automation:
      values:
        charts:
          # Cluster Configuration App of App Chart
          cluster-configs:
            values:
              charts:
                # OpenShift Data Foundations
                odf:
                  disabled: true
 
                 # Operators App of App Chart
                operators:
                  values:
                    charts:
                      odf-operator:
                        disabled: true
```
Will disable the generation of ODF and ODF operator.

### CODE REVIEW

**Comment by jordigilh** [comment]
@sabre1041 @nasx please take a look.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by sabre1041** [comment]
@jordigilh got some conflict now

**Comment by jordigilh** [comment]
@sabre1041 it's ready.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
