### PR TITLE
Adding SSH public key to SSH secret.

### PR DESCRIPTION
**Pull request by nasx**

### CODE REVIEW

**Review by chadhellyea — COMMENTED** [review]
Instead of pushing the key in the repo should we add it as a secret in the repository? Sry i come from a very security minded background (DOD/Energy)

**Comment by sabre1041** [comment]
@chadhellyea its contained within a `SealedSecret` resource and is protected

**Comment by chadhellyea** [comment]
Ah its sealed whew!

**Review by sabre1041 — APPROVED** [review]

**Comment by chadhellyea** [comment]
lgtm

**Pull request merged**
