### PR TITLE
Fix kustomize build parameter

### PR DESCRIPTION
**Pull request by pkliczewski**
Spelling mistake in a paramater.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Review by nasx — COMMENTED** [review]
@sabre1041 I know `--load_restrictor` is technically correct but no one uses that version of kustomize anymore. This affects #134.

**Comment by pkliczewski** [comment]
@nasx I fails for me when i run it. Complaining about unknown paramater

**Comment by nasx** [comment]
> @nasx I fails for me when i run it. Complaining about unknown paramater

Yeah you are probably using a more recent version of kustomize. I think the issue is OpenShift technically supports (or at some point only supported) a version of kustomize that still uses `--load_restrictor` vs. `--load-restrictor`. @sabre1041 has the details, will let him chime in. The fix is to update the docs with the required version of kustomize or accept this PR.

**Comment by sabre1041** [comment]
@nasx the issue as @nasx explained is due to the version of Kustomize. Most (up to very recent versions of Kuberentes and by extension OpenShift) used Kustomize 3.x instead of the more current Kustomize 4.x. This is also the same version that ArgoCD uses internally as well. We just need to update the docs to be explicit on the command used for each version

**Comment by pkliczewski** [comment]
Yeah, it could be the reason. I am using `{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:24:28Z GoOs:linux GoArch:amd64}`

**Comment by pkliczewski** [comment]
Please reopen if you think we need it.

**Pull request closed without merging**
